[project]
site_name = "AVPS DRHFPNC"
site_description = "Catalogue complet des AVPs de la DRHFPNC"
site_url = "https://adriens.github.io/avps/"
repo_url = "https://github.com/adriens/avps"
repo_name = "adriens/avps"
docs_dir = "docs"
site_dir = "site"

[project.theme]
name = "material"
language = "fr"
features = ["navigation.top", "navigation.tracking", "navigation.footer", "navigation.sections", "search.suggest", "search.highlight"]

# Mode sombre par défaut (Slate en premier)
[[project.theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle.icon = "material/brightness-4"
toggle.name = "Passer au mode clair"

[[project.theme.palette]]
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "material/brightness-7"
toggle.name = "Passer au mode sombre"

[project.extra]
copyright = """
Copyright &copy; 2026 adriens<br>
<small>Propulsé par <a href='https://github.com/opt-nc/zensical' target='_blank'>Zensical</a></small>
"""
