# Configuration Zensical
site_name = "AVPS DRHFPNC"
site_description = "Catalogue complet des AVPs de la DRHFPNC"
site_url = "https://adriens.github.io/avps/"
repo_url = "https://github.com/adriens/avps"
repo_name = "adriens/avps"
docs_dir = "docs"
output_dir = "site"

[theme]
name = "material"
primary_color = "#212121"
accent_color = "#ff4081"
default_mode = "dark"

[[theme.palette]]
scheme = "slate"
primary = "black"
accent = "pink"
toggle = { icon = "material/brightness-4", name = "Switch to light mode" }

[extra]
footer_message = "Généré avec ❤️ par Zensical"

[navigation]
show_reading_time = false
show_last_updated = true
